### ISSUE TITLE
Wildcard / multi TXT support

### ISSUE THREAD

**Issue by genofire** [loewexy/pdns-acme#6]
It is not possible to set up a 2. acme-challenge for "*.example.org".
Both work on same TXT record of "example.org"

e.g. config:

```json
{
    "config": {
        "server": "https://example.org/",
        "deploy-wait": 120
    },
    "domains": {
        "example.org": 15,
        "*.example.org": 364,
    },
    "certs": {
        "example.org": {
            "alias": [ "*.example.org"]
        }
    }
}
```

**Comment by loewexy** [comment]
So what is your problem? What does not work in this case?

**Comment by genofire** [comment]
for the challenge of `*.example.org` he detect it as domain `example.org` so he use the record 14 twice (and only one of the two needed challenges works)

**Comment by loewexy** [comment]
I can not see what the problem is, the validation record for *.example.com and example.com should both be _acme-challenge.example.com. So it should work if the same record is reused. But I am also not clear why this should happen.

I will try a test setup if I can find the time.

**Comment by genofire** [comment]
Any updates -> certs are expired ;(

**Comment by lukavia** [comment]
The problem is that dehydrated would process 2 challanges from letsencrypt both with the same domain: example.org but diffrent values. This is how it suppose to work. 
So in the end you have to have 2 dns txt records.

So in the hook file when deploy_challenge is called the first param is always example.org instead of *.example.org. 
And this leads for pdns-acme to only update the first record (id 15) in the given example and never the second (364). 
Once dehydrated gets to responding to challanges you would always get "invalid" since only one dns record is set. 

Unfortunatelly in the current architecture this is not easy to solve. 
may be the config should be "domains": {
        "example.org": [15, 364] 
And then the hook would check to not use the same ID for a domain twice

**Comment by loewexy** [comment]
Oh okay I guess I understand the problem here. I thought that dehydrated will give you the real domain name for which a challenge should be deployed. And we get the problem that it reuses the same one. Lets discuss this further in you Pullrequest.
